web:
  build: .
  container_name: koken_apache_1
  ports:
  - 153:80
  links:
  - mariadb:db
  environment:
  - MYSQL_DATABASE=web
  - MYSQL_USER=admin
  - MYSQL_PASSWORD=Neu1ones1602
  - MYSQL_ROOT_PASSWORD=Neu1ones1602
  volumes:
  - ./:/var/www/html
mariadb:
    image: mariadb:10.1
    container_name: koken_mariadb_1
    environment:
    - MYSQL_DATABASE=web
    - MYSQL_USER=admin
    - MYSQL_PASSWORD=Neu1ones1602
    - MYSQL_ROOT_PASSWORD=Neu1ones1602
    volumes:
    - /var/lib/mysql
    ports:
    - 15333:3306